db={
    "user":"codakcodak",
    "password":"dkdrmaghEl83!",
    "host":"miniter.cnvmcb0pomhk.ap-northeast-2.rds.amazonaws.com",
    "port":3306,
    "database":"miniter"
}
JWT_SECRET_KEY="codak"
test_db={
    'user':'codakcodak',
    'password':'dkdrmaghEl83!',
    'host':'localhost',
    'port':3306,
    'database':'test_miniter'
}
test_config={
    'DB_URL':f"mysql+mysqlconnector://{test_db['user']}:{test_db['password']}@{test_db['host']}:{test_db['port']}/{test_db['database']}?charset=utf8",
    'JWT_SECRET_KEY':"codak"
}
DB_URL=f"mysql+mysqlconnector://{test_db['user']}:{test_db['password']}@{test_db['host']}:{test_db['port']}/{test_db['database']}?charset=utf8"
test_config={
    'DB_URL':f"mysql+mysqlconnector://{test_db['user']}:{test_db['password']}@{test_db['host']}:{test_db['port']}/{test_db['database']}?charset=utf8",
    'JWT_SECRET_KEY':"codak"
}

UPLOAD_DIR='./profile_pictures'